/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class VectorOfDoubleVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorOfDoubleVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorOfDoubleVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoolPropJNI.delete_VectorOfDoubleVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorOfDoubleVector() {
    this(CoolPropJNI.new_VectorOfDoubleVector__SWIG_0(), true);
  }

  public VectorOfDoubleVector(long n) {
    this(CoolPropJNI.new_VectorOfDoubleVector__SWIG_1(n), true);
  }

  public long size() {
    return CoolPropJNI.VectorOfDoubleVector_size(swigCPtr, this);
  }

  public long capacity() {
    return CoolPropJNI.VectorOfDoubleVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CoolPropJNI.VectorOfDoubleVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CoolPropJNI.VectorOfDoubleVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CoolPropJNI.VectorOfDoubleVector_clear(swigCPtr, this);
  }

  public void add(DoubleVector x) {
    CoolPropJNI.VectorOfDoubleVector_add(swigCPtr, this, DoubleVector.getCPtr(x), x);
  }

  public DoubleVector get(int i) {
    return new DoubleVector(CoolPropJNI.VectorOfDoubleVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, DoubleVector val) {
    CoolPropJNI.VectorOfDoubleVector_set(swigCPtr, this, i, DoubleVector.getCPtr(val), val);
  }

}
